### ISSUE TITLE
strange work around

### ISSUE THREAD

**Issue by sonnwendjoch** [dired/PMCA-HDMICam#1]
i downloaded the apk but i got some sort of error, but by downloading the debug version it actually worked.

the error massege:
File "pmca-gui.py", line 78, in do
  File "pmca\commands\usb.py", line 300, in installCommand
  File "pmca\commands\usb.py", line 73, in installApp
Exception: Communication error 100: Error completed

i actualy made an account just to let you know because i love the idea of this app but felt you needed to know.
(by the way i use an nex 6)

**Comment by dired** [comment]
Wow, thanks so for much trying it out and registering for letting me know!  <3
To be honest I didn't try out the non-debug version, I was just happy that I was able to build the release variant and just assumed that it should work the same, my apologies.
Thanks again for not giving up and finding the solution yourself, great job!
Makes me glad to hear that you like the idea as well :)

I will change the release now and remove the non-debug version and correct the text. I won't work on making the release variant functional, since it's essentially just the saving the space of 20KB, not like that we get any actual benefits from having it and if I improve something I want it to be important. I would also even leave the "-debug" in the filename since it's the truth - I add a not about it in the release.

By the way, maybe you didn't question it, but I found out (actually read it on someone elses PMCADemo fork I believe - and tested it) that the camera "parameter" settings (ISO etc) you make outside of the app persist in the app (but as "advertised" can't be changed in the current basic state). For example, in manual mode, you set the iso - the same iso persists in the app and can't be changed. For example in Auto Mode, I set the ISO to auto, and in the app the same "brightness-related" behaviour persists (which was beneficial to my case).

I will change the readme sometime soon when I have some more time for it, to write a short note about these "persistent camera parameters", correct some parts and make a new gif (found it a bit confusing).

By the way it would interest me if you have an idea about a feature that would be beneficial for you?
I use the hx400v for recording timelapses of my ("plant"-)aquarium / stream it 24/7 (works rock-solid).
I was thinking that as with any other webcam, the real next step would be to be able to set as many parameters possible remotely/from the computer. Unfortunately can't be done the same as with webcams since the capture card can't "propagate" settings from the cam, and would require the cam to be in wifi, and a separate gui-app (that someone would have to write cross-platform (not too hard but not too easy for me)) to deliver the changes in settings to the cam, and the implementation in the pmca-app to receive from the remote and setting the actual camera parameters using the (existing) sony library. Bit too much work, if not many people want it (but it would be cool to zoom remotely).
I now started thinking it doesn't make sense to be able to "use the buttons" while in clean hdmi mode, because it makes the camera wiggle - not a webcam experience at all.

**Comment by dired** [comment]
I removed the non-functional variant from the release and added some explanation in the description of the release, that we are fine to just keep using the debug variant (btw (obviously) the first release was also the debug variant).
[see here](https://github.com/dired/PMCA-HDMICam/releases/tag/v0.2)

As this closes the issue, I created a discussion so that I could handle the closing of the issue now and so that we could continue the conversation over there
[discussion for improvements](https://github.com/dired/PMCA-HDMICam/discussions/3)
